"""add_social_score_history_table

Revision ID: 0f72d9b4974b
Revises: 394571d76d3a
Create Date: 2025-11-25 17:17:53.986359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0f72d9b4974b'
down_revision: Union[str, Sequence[str], None] = '394571d76d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Reuse existing taskstatus enum (created in earlier migration)
    taskstatus_enum = postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='taskstatus', create_type=False)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['clinical_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_score_history_episode_id'), 'social_score_history', ['episode_id'], unique=False)
    op.create_table('task_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('old_status', taskstatus_enum, nullable=True),
    sa.Column('new_status', taskstatus_enum, nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_history_task_id'), 'task_status_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_history_task_id'), table_name='task_status_history')
    op.drop_table('task_status_history')
    op.drop_index(op.f('ix_social_score_history_episode_id'), table_name='social_score_history')
    op.drop_table('social_score_history')
    # ### end Alembic commands ###
