"""add clinical episodes table

Revision ID: 508c5aec91ad
Revises: b27a05b3af7d
Create Date: 2025-10-16 10:07:12.043047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508c5aec91ad'
down_revision: Union[str, Sequence[str], None] = 'b27a05b3af7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('discharge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_discharge', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCHARGED', 'TRANSFERRED', 'CANCELLED', name='episodestatus'), nullable=False),
    sa.Column('bed_id', sa.UUID(), nullable=True),
    sa.Column('admission_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_episodes_bed_id'), 'clinical_episodes', ['bed_id'], unique=False)
    op.create_index(op.f('ix_clinical_episodes_patient_id'), 'clinical_episodes', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_episodes_patient_id'), table_name='clinical_episodes')
    op.drop_index(op.f('ix_clinical_episodes_bed_id'), table_name='clinical_episodes')
    op.drop_table('clinical_episodes')
    # ### end Alembic commands ###
