"""create patients table

Revision ID: 8dd25d0a2b3a
Revises: 
Create Date: 2025-10-13 16:33:19.606023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd25d0a2b3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_identifier', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=320), nullable=False),
    sa.Column('last_name', sa.String(length=320), nullable=False),
    sa.Column('rut', sa.String(length=320), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_medical_identifier'), 'patients', ['medical_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_medical_identifier'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
