"""add episode documents table

Revision ID: 98694da00aa6
Revises: 508c5aec91ad
Create Date: 2025-10-16 10:12:17.876260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98694da00aa6'
down_revision: Union[str, Sequence[str], None] = '508c5aec91ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('MEDICAL_REPORT', 'LAB_RESULT', 'PRESCRIPTION', 'IMAGING', 'CONSENT_FORM', 'DISCHARGE_SUMMARY', 'TREATMENT_PLAN', 'NURSING_NOTES', 'OTHER', name='episodedocumenttype'), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['clinical_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_documents_episode_id'), 'episode_documents', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_documents_episode_id'), table_name='episode_documents')
    op.drop_table('episode_documents')
    # ### end Alembic commands ###
