"""add_episode_identifier_to_clinical_episodes

Revision ID: a978d460e6cf
Revises: a5b6c7d8e9f0
Create Date: 2025-12-02 18:02:02.019621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a978d460e6cf'
down_revision: Union[str, Sequence[str], None] = 'a5b6c7d8e9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_episodes', sa.Column('episode_identifier', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_clinical_episodes_episode_identifier'), 'clinical_episodes', ['episode_identifier'], unique=False)
    op.drop_constraint(op.f('grd_norms_grd_id_key'), 'grd_norms', type_='unique')
    op.drop_index(op.f('ix_grd_norms_grd_id'), table_name='grd_norms')
    op.create_index(op.f('ix_grd_norms_grd_id'), 'grd_norms', ['grd_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grd_norms_grd_id'), table_name='grd_norms')
    op.create_index(op.f('ix_grd_norms_grd_id'), 'grd_norms', ['grd_id'], unique=False)
    op.create_unique_constraint(op.f('grd_norms_grd_id_key'), 'grd_norms', ['grd_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_clinical_episodes_episode_identifier'), table_name='clinical_episodes')
    op.drop_column('clinical_episodes', 'episode_identifier')
    # ### end Alembic commands ###
