"""add clinical episode information table

Revision ID: b32340fbec94
Revises: 98694da00aa6
Create Date: 2025-10-16 10:15:35.092339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b32340fbec94'
down_revision: Union[str, Sequence[str], None] = '98694da00aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_episode_information',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('info_type', sa.Enum('DIAGNOSIS', 'TREATMENT', 'MEDICATION', 'ALLERGY', 'VITAL_SIGNS', 'LAB_RESULTS', 'NOTES', 'PROGRESS', 'DISCHARGE_PLANNING', 'OTHER', name='episodeinfotype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['clinical_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_episode_information_episode_id'), 'clinical_episode_information', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_episode_information_episode_id'), table_name='clinical_episode_information')
    op.drop_table('clinical_episode_information')
    # ### end Alembic commands ###
