"""add_episode_identifier_to_clinical_episodes

Revision ID: bc6231949f83
Revises: g4b5c8d2e1f3
Create Date: 2025-12-02 22:20:15.936492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6231949f83'
down_revision: Union[str, Sequence[str], None] = 'g4b5c8d2e1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_episodes', sa.Column('episode_identifier', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_clinical_episodes_episode_identifier'), 'clinical_episodes', ['episode_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_episodes_episode_identifier'), table_name='clinical_episodes')
    op.drop_column('clinical_episodes', 'episode_identifier')
    # ### end Alembic commands ###
