"""add room column to bed

Revision ID: bf1de3e8398f
Revises: a1e6596d27b1
Create Date: 2025-10-17 11:44:47.979680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1de3e8398f'
down_revision: Union[str, Sequence[str], None] = 'a1e6596d27b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('beds', sa.Column('room', sa.String(length=320), nullable=True))
    
    # Update existing beds with default room numbers
    op.execute("""
        UPDATE beds 
        SET room = 'ROOM-' || id::text
        WHERE room IS NULL
    """)
    
    # Make column non-nullable
    op.alter_column('beds', 'room', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beds', 'room')
    # ### end Alembic commands ###
